package com.ngambis.ai.dtos.response;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for a quiz/flashcard item generated by AI from document text.
 */
@Data
@NoArgsConstructor
public class GeneratedQuizItemDto {

    private String itemType;       // "MULTIPLE_CHOICE" or "ESSAY"
    private String questionText;
    private String referenceText;

    // MULTIPLE_CHOICE only
    private String options;        // JSON array string e.g. ["A","B","C","D"]
    private String correctAnswer;
}
